
# <font color=" #009933"><b>Python</b><br></font>

Python is a popular, high-level programming language known for its simplicity and readability, making it a great choice for both <br>beginners and experienced developers. Here are some key points about Python

##### <font color="#e65c00"><b>1. Basic Features of Python</b><br></font>

<b> Simple Syntax:</b>
   Python's syntax is clean and easy to understand, which makes code more readable and reduces the learning curve.
    
<b>Interpreted Language:</b> 
    Python is an interpreted language, which means code is executed line-by-line, making debugging easier.

<b>Dynamically Typed: </b>
    Variables in Python do not require an explicit declaration to reserve memory space, which makes coding faster and simpler.
    
<b>Versatile: </b>
    It supports multiple programming paradigms, including procedural, object-oriented, and functional programming.






.

##### <font color="#e65c00"><b>2. Common Uses of Python</b><br></font>

<b>Web Development: </b>
    Frameworks like Django and Flask make Python a popular choice for creating web applications.

<b>Data Science and Machine Learning: </b>
    Python's powerful libraries like NumPy, pandas, TensorFlow, and scikit-learn are widely used in data analysis and machine learning.

<b>Automation/Scripting: </b>
    Python is often used to automate repetitive tasks, like file management or data extraction.
    
<b>Software Development: </b>
    It can be used for building applications, developing software prototypes, and game development.

##### <font color="#e65c00"><b>3. Core Concepts</b><br></font>

<b>Variables and Data Types:</b> 
Python supports various data types, such as integers, floats, strings, lists, tuples, and dictionaries.
  
<b>Control Structures:</b> 
 Includes if-else statements, loops (for and while), and control flow keywords like break and continue.

<b>Functions: </b> 
Functions in Python are defined using the def keyword, and they help organize code and make it reusable.

<b>Modules and Packages: </b> 
Code can be organized into modules and packages, promoting reusability and maintainability.

In [ ]:
# 1.Variables and Data Types
integer_num = 10         # Integer
float_num = 20.5         # Float
string_text = "Hello!"   # String
boolean_value = True     # Boolean

print(integer_num, float_num, string_text, boolean_value)

In [ ]:
# 2.Control statements

# If-else statement
age = 20
if age >= 18:
    print("You are an adult.")
else:
    print("You are a minor.")

# For loop
for i in range(5):
    print("Iteration:", i)

# While loop
count = 0
while count < 3:
    print("Count is:", count)
    count += 1


In [ ]:
# 3.Function definition
def greet(name):
    return f"Hello, {name}!"

# Calling the function
message = greet("Alice")
print(message)


In [ ]:
# 4.Modules and Packages
# Importing a module
import math

# Using a function from the math module
square_root = math.sqrt(36)
print("Square root of 36 is:", square_root)


##### <font color="#e65c00"><b>4. Object-Oriented Programming (OOP)</b><br></font>

<b>Classes and Objects: </b>
Python supports OOP principles like encapsulation, inheritance, and polymorphism.

<b>Creating Classes: </b>
Classes are defined using the class keyword and allow you to create objects with properties (attributes) and behaviors (methods).

In [ ]:
# Define a class called Person
class Person:
    # Constructor method to initialize the attributes
    def __init__(self, name, age):
        self.name = name  # Attribute
        self.age = age    # Attribute

    # Method to display the person's details
    def display_info(self):
        print(f"Name: {self.name}, Age: {self.age}")

# Create an object (instance) of the Person class
person1 = Person("Alice", 25)

# Call the method to display person's details
person1.display_info()

In [ ]:
# Define a class called Student that inherits from Person
# Inheritance allows one class to inherit attributes and methods from another class
class Student(Person):
    def __init__(self, name, age, student_id):
        super().__init__(name, age)  # Call the constructor of the parent class
        self.student_id = student_id  # New attribute for Student class                 

    # Method to display student details
    def display_student_info(self):
        self.display_info()  # Call the method from the parent class
        print(f"Student ID: {self.student_id}")

# Create an object of the Student class
student1 = Student("Bob", 21, "S12345")

# Call the method to display student details
student1.display_student_info()

#student1.display_info()


In [ ]:
# Define a class with encapsulation
# Encapsulation is about data hiding and controlling access.
class BankAccount:
    def __init__(self, owner, balance):
        self.owner = owner  # Public attribute
        self.__balance = balance  # Private attribute (prefix with double underscore)

    # Method to deposit money
    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited: {amount}. New balance: {self.__balance}")

    # Method to withdraw money
    def withdraw(self, amount):
        if 0 < amount <= self.__balance:
            self.__balance -= amount
            print(f"Withdrew: {amount}. New balance: {self.__balance}")
        else:
            print("Insufficient funds or invalid amount!")

    # Method to check the balance
    def get_balance(self):
        return self.__balance

# Create an object of the BankAccount class
account = BankAccount("Charlie", 1000)

# Accessing methods to interact with the account
#account.deposit(500)
account.withdraw(300)
print("Final balance:", account.get_balance())



##### <font color="#e65c00"><b>5. Python Libraries</b><br></font>

<b>NumPy:</b>
    For numerical computing, handling large datasets, and performing operations on multi-dimensional arrays.

<b>pandas: </b>
    For data manipulation and analysis.

<b>Matplotlib/Seaborn:</b> 
    For data visualization.
    



# <font color=" #000099 ,"><b>NumPy</b><br></font>


<font color="blue"> <b>Prerequisites:<br></b></font>


-- Basic knowledge of Python programming.<br>
-- Familiarity with Python's data structures (lists, tuples, dictionaries).<br>
-- Some understanding of mathematical operations and arrays.<br>
-- install numpy library pip install numpy


What is Numpy..?<br>
<br>
NumPy (Numerical Python) is a powerful library in Python used for numerical and scientific computing.<br> NumPy is widely used in data science, machine learning, artificial intelligence, and scientific computing due to its efficiency and versatility.

### Key Features of NumPy
--> N-Dimensional Arrays<br>
--> Mathematical Operations<br>
--> Broadcasting<br>
--> Linear Algebra and Matrix Operations<br>
--> Integration with Other Libraries<br>
--> Memory Usage<br>
--> Data Manipulation Capabilities<br>

##### Why Use NumPy?



.

-- Performance <br>
-- Ease of Use <br>
-- Scalability <br>

##### Applications of NumPy


.

-- Data Science and Machine Learning<br>
-- Scientific Computing<br>
-- Financial Analysis<br>

##### <font color="blue"><b>Understanding NumPy Arrays (ndarrays)</b><br></font>

-----> NumPy arrays (ndarrays) are the main data structure in NumPy, designed to handle large datasets efficiently.

In [ ]:
# Example of a NumPy array vs. Python list operation:

import numpy as np

# Using a Python list
python_list = [1, 2, 3, 4]
result_list = [x * 2 for x in python_list]
print("Python list result:", result_list)  # Output: [2, 4, 6, 8]

# Using a NumPy array
numpy_array = np.array([1, 2, 3, 4])
result_array = numpy_array * 2
print("NumPy array result:", result_array)  # Output: [2, 4, 6, 8]


##### <font color="blue"><b>Creating Arrays</b><br></font>
-----> NumPy provides several functions to create arrays quickly and easily:

In [ ]:
#array(): Converts a Python list to a NumPy array.

arr = np.array([1, 2, 3, 4])
print(arr)  

In [ ]:
#zeros(): Creates an array filled with zeros.

arr = np.zeros((2, 3))
print(arr)

In [ ]:
#ones(): Creates an array filled with ones.

arr = np.ones((3, 2))
print(arr)

In [ ]:
#empty(): Creates an uninitialized array (contains random values).

arr = np.empty((2, 2))
print(arr)
# Output: Random uninitialized values

In [ ]:
#full(): Creates an array filled with a specified value.

arr = np.full((2, 2), 7)
print(arr)

In [ ]:
#arange(): Creates an array with a range of values (similar to Python's range()).

arr = np.arange(0, 10, 2)
print(arr)

In [ ]:
#linspace(): Creates an array of evenly spaced values between a start and end value.

arr = np.linspace(0, 1, 5)
print(arr)  

In [ ]:
#eye(): Creates an identity matrix.

arr = np.eye(3)
print(arr)

In [ ]:
#random(): Creates an array with random values.

arr = np.random.rand(2, 2)
print(arr)
# Output: Random values between 0 and 1


##### <font color="blue"><b>Array Data Types</b><br></font>
-----> You can specify the data type of an array using the dtype parameter.

In [ ]:
arr = np.array([1, 2, 3], dtype='float64')
print(arr)       
print(arr.dtype)  

#Specifying the data type ensures that all elements in the array are of the same type

##### <font color="blue"><b>Array Attributes</b><br></font>
-----> NumPy arrays have several useful attributes that provide information about the array.

In [ ]:
# shape: Returns the dimensions of the array (rows, columns).

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3)

In [ ]:
#dtype: Returns the data type of the elements in the array.

print(arr.dtype)  # Output: int64 (or int32 depending on your system)

In [ ]:
#ndim: Returns the number of dimensions of the array.

print(arr.ndim)  

In [ ]:
#size: Returns the total number of elements in the array.

print(arr.size)  # Output: 6

In [ ]:
#itemsize: Returns the size in bytes of each element in the array.

print(arr.itemsize) 

<b>shape:</b> Useful for understanding the structure of multi-dimensional arrays.<br>

<b>dtype:</b> Important for ensuring that calculations are performed with the correct data type.<br>

<b>ndim:</b> Indicates whether the array is 1D, 2D, or multi-dimensional.<br>

<b>size:</b> Helps determine how many elements are in the array.

##### <font color="blue"><b>Array Operations</b><br></font>

##### <font color="#006666">Basic Operations:<br></font>

-----> Arithmetic operations (addition, subtraction, multiplication, division, modulus).


In [ ]:
import numpy as np

# Creating two NumPy arrays
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# Addition
addition = array1 + array2
print("Addition:", addition)  

# Subtraction
subtraction = array2 - array1
print("Subtraction:", subtraction)  

# Multiplication
multiplication = array1 * array2
print("Multiplication:", multiplication)  

# Division
division = array2 / array1
print("Division:", division)  

# Modulus
modulus = array2 % array1
print("Modulus:", modulus)  


##### <font color="#006666">Universal Functions (ufuncs):<br></font>

-----> Universal functions, or ufuncs, are functions that perform element-wise operations on arrays. NumPy provides many built-in ufuncs that are optimized for speed and efficiency.

In [ ]:
#Example: Using Universal Functions

# Creating two NumPy arrays
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# Using np.add() to add two arrays
add_result = np.add(array1, array2)
print("Using np.add():", add_result) 

# Using np.subtract() to subtract two arrays
subtract_result = np.subtract(array2, array1)
print("Using np.subtract():", subtract_result)  

# Using np.multiply() to multiply two arrays
multiply_result = np.multiply(array1, array2)
print("Using np.multiply():", multiply_result)  

# Using np.divide() to divide two arrays
divide_result = np.divide(array2, array1)
print("Using np.divide():", divide_result)  


##### <font color="black">Benefits of Using Universal Functions<br><br></font>


.

Speed: Ufuncs are implemented in C, making them faster than regular Python functions.<br>

Convenience: They simplify code by allowing operations directly on arrays without writing loops.<br>

Broadcasting: They work seamlessly with arrays of different shapes.<br>

##### <font color="blue"><b>Indexing and Slicing</b><br></font>


##### <font color="#006666">Array Indexing<br></font>
----> Array indexing allows you to access individual elements within a NumPy array. You can use both positive and negative indices for this purpose.

In [ ]:
#Example: Accessing Elements with Positive and Negative Indices
import numpy as np

# Creating a 1D array
arr = np.array([10, 20, 30, 40, 50])

# Accessing elements using positive indices
print("Element at index 0:", arr[0]) 
print("Element at index 3:", arr[3]) 

# Accessing elements using negative indices
print("Element at index -1:", arr[-1])  
print("Element at index -3:", arr[-3])  



##### <font color="#006666">Slicing Arrays<br></font>

----> Slicing is used to extract a part of the array. The syntax for slicing is arr[start:end:step].

In [ ]:
#Example: Slicing Arrays

# Creating a 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Slicing from index 1 to 5 (excluding 5)
slice1 = arr[1:5]
print("Slice from index 1 to 5:", slice1) 

# Slicing with a step of 2
slice2 = arr[0:7:2]
print("Slice with a step of 2:", slice2) 

# Slicing with negative indices
slice3 = arr[-5:-1]
print("Slice using negative indices:", slice3)  



##### <font color="#006666">Fancy Indexing and Boolean Masking<br></font>

----> Fancy indexing allows you to access elements of an array using another array or list of indices, while Boolean masking allows you to filter the array using conditions.

In [ ]:
#Example: Fancy Indexing

# Using a list of indices to access specific elements
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
fancy_indexing = arr[indices]
print("Fancy indexing result:", fancy_indexing)  # Output: [10 30 50]


In [ ]:
#Example: Boolean Masking

# Using a condition to filter elements
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 30
print("Boolean mask:", mask)  # Output: [False False False  True  True]

# Applying the mask to get the filtered array
filtered_array = arr[mask]
print("Filtered array:", filtered_array)  # Output: [40 50]



##### <font color="#006666">Modifying Arrays<br></font>
----> You can modify specific elements or entire sections of a NumPy array using indexing or slicing.

In [ ]:
#Example: Modifying Specific Elements

# Creating a 1D array
arr = np.array([10, 20, 30, 40, 50])

# Modifying a single element
arr[2] = 100
print("Modified array:", arr)  # Output: [ 10  20 100  40  50]


In [ ]:
#Example: Modifying Sections of an Array

# Creating a 1D array
arr = np.array([10, 20, 30, 40, 50])

# Modifying a section of the array using slicing
arr[1:4] = [200, 300, 400]
print("Array after modifying a section:", arr)  # Output: [ 10 200 300 400  50]



##### <font color="blue"><b>Reshaping and Resizing Arrays</b><br></font>

In NumPy, you can easily change the shape and structure of arrays using functions like reshape() and flatten().<br> You can also combine (concatenate) or break (split) arrays using functions like concatenate(), vstack(), hstack(), split(), and hsplit().

In [ ]:
#Example: Using reshape() 

import numpy as np

# Creating a 1D array with 9 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshaping the array to 3x3
reshaped_arr = np.reshape(arr, (3, 3))
print("Reshaped array (3x3):")
print(reshaped_arr)

In [ ]:
#Example: Using flatten()

# Flattening the 2D array back to 1D
flattened_arr = reshaped_arr.flatten()
print("Flattened array:")
print(flattened_arr)



##### <font color="#006666">Concatenate<br></font>

In [ ]:
#Example: Using concatenate()

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenating along axis 0 (vertically)
concat_vertical = np.concatenate((arr1, arr2), axis=0)
print("Vertical concatenation:")
print(concat_vertical)


# Concatenating along axis 1 (horizontally)
concat_horizontal = np.concatenate((arr1, arr2), axis=1)
print("Horizontal concatenation:")
print(concat_horizontal)

# NOte: concatenate() can merge arrays along any axis (axis 0 for vertical, axis 1 for horizontal).

In [ ]:
#Example: Using vstack() and hstack()

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Vertical stack (row-wise)
vstacked = np.vstack((arr1, arr2))
print("Vertical stack (vstack):")
print(vstacked)

# Horizontal stack (column-wise)
hstacked = np.hstack((arr1, arr2))
print("Horizontal stack (hstack):")
print(hstacked)




##### <font color="#006666">Splitting Arrays<br></font>

In [ ]:
#Example: Using split()

# Creating an array with 9 elements
arr = np.arange(9)

# Splitting into 3 equal parts
split_arr = np.split(arr, 3)
print("Split into 3 parts:")
print(split_arr)


<font color="blue"> <b>Exercise<br></b></font>

<font color="#9900FF">Splitting Odd Numbers into a Separate Array</font>

##### <font color="blue"><b>Statistical and Mathematical Functions<br></b></font>
----> NumPy provides several functions for basic statistical operations on arrays, including mean, median, sum, minimum, maximum, standard deviation, and variance.

<b>mean():</b> Returns the average of the array.<br>

<b>median():</b> Returns the median value.<br>

<b>sum():</b> Returns the sum of all elements in the array.<br>

<b>min() and max():</b> Return the minimum and maximum values, respectively.<br>

<b>std():</b> Returns the standard deviation.<br>

<b>var():</b> Returns the variance.<br>

In [ ]:
import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Mean
mean_value = np.mean(arr)
print("Mean:", mean_value)  # Output: 5.0

# Median
median_value = np.median(arr)
print("Median:", median_value)  # Output: 5.0

# Sum
sum_value = np.sum(arr)
print("Sum:", sum_value)  # Output: 45

# Minimum value
min_value = np.min(arr)
print("Min:", min_value)  # Output: 1

# Maximum value
max_value = np.max(arr)
print("Max:", max_value)  # Output: 9

# Standard deviation
std_value = np.std(arr)
print("Standard Deviation:", std_value)  # Output: 2.581988897471611

# Variance
var_value = np.var(arr)
print("Variance:", var_value)  # Output: 6.666666666666667



##### <font color="#006666">Aggregation Functions<br></font>

----> Aggregation functions in NumPy allow you to compute cumulative sums and products across an array.

In [ ]:
#Example: Cumulative Sum and Cumulative Product

# Cumulative sum (cumsum)
cumsum_value = np.cumsum(arr)
print("Cumulative Sum:", cumsum_value)  
# Output: [ 1  3  6 10 15 21 28 36 45]

# Cumulative product (cumprod)
cumprod_value = np.cumprod(arr)
print("Cumulative Product:", cumprod_value)  
# Output: [     1      2      6     24    120    720   5040  40320 362880]


##### <font color="#006666">Random Sampling<br></font>

----> NumPy provides powerful random number generation functions through the np.random module. You can generate random numbers and control reproducibility using a seed.

<b>rand():</b> Generates random numbers between 0 and 1 from a uniform distribution.<br>

<b>randn():</b> Generates random numbers from a normal (Gaussian) distribution.<br>

<b>seed():</b> Sets a random seed to ensure reproducibility of random numbers.<br>

In [ ]:
#Example: Random Number Generation

# Generating a random array of floats between 0 and 1 (uniform distribution)
random_values = np.random.rand(3)
print("Random numbers (uniform distribution):", random_values)
# Output: Random numbers like [0.643267 0.675564 0.22345]

# Generating random values from a normal distribution
random_normal = np.random.randn(3)
print("Random numbers (normal distribution):", random_normal)
# Output: Random numbers like [ 0.497  -1.392  0.078]

# Setting a random seed for reproducibility
np.random.seed(42)
random_seeded = np.random.rand(3)
print("Seeded random numbers:", random_seeded)
# Output: [0.37454012 0.95071431 0.73199394]


<font color="blue"> <b>Exercise<br></b></font>

<font color="#9900FF">Select a Random Name from a List</font>


##### <font color="#006666">Working with Matrices<br></font>

----> In NumPy, matrices are represented as 2D arrays. Matrix operations like multiplication, transpose, determinant, inverse, and solving linear equations can be performed using NumPy functions.

In [ ]:
#a) Creating Matrices 

import numpy as np

# Creating a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:")
print(matrix)
# Output:
# [[1 2]
#  [3 4]]

In [ ]:
#b) Dot Product and Matrix Multiplication

# Creating two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Dot product (same as element-wise multiplication for 1D arrays)
dot_product = np.dot(matrix1, matrix2)
print("Dot product (matrix multiplication):")
print(dot_product)
# Output:
# [[19 22]
#  [43 50]]

# Matrix multiplication using @ operator
matrix_mult = matrix1 @ matrix2
print("Matrix multiplication (@ operator):")
print(matrix_mult)
# Output:
# [[19 22]
#  [43 50]]


In [ ]:
#c) Transpose of a Matrix<br>

# Transposing the matrix
transpose_matrix = matrix.T
print("Transpose of the matrix:")
print(transpose_matrix)
# Output:
# [[1 3]
#  [2 4]]

<font color="blue"> <b>Exercise<br></b></font>

<font color="#9900FF">Transpose and Sum of Diagonal Elements for a 3×3 Matrix..?</font>

In [ ]:
#d) Determinant of the matrix
determinant = np.linalg.det(matrix)
print("Determinant of the matrix:", determinant)
# Output: -2.0000000000000004

#Note: det(A)=ad−bc


In [ ]:
#e) Inverse of a Matrix
#Note: The inverse of a matrix exists if and only if the matrix is square and its determinant is non-zero.

# Inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)
print("Inverse of the matrix:")
print(inverse_matrix)
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]


A−1 =1/det(A) ×[d −b,-c a]

Solving Linear Equations

2x+y=5<br>
x+2y=6

In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, 1],
              [1, 2]])

# Result matrix B
B = np.array([5, 6])

# Solving for x
solution = np.linalg.solve(A, B)
print("Solution (x and y values):", solution)


<font color="blue"> <b>Exercise<br></b></font>

<font color="#9900FF">Matrix Multiplication Without Built-in Functions..?</font>


##### <font color="#006666">Sorting Arrays<br></font>

In [ ]:
#Example: Sorting Arrays

import numpy as np

# Creating an array
arr = np.array([3, 1, 2, 5, 4])

# Sorting the array in ascending order
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)
# Output: Sorted array: [1 2 3 4 5]


<font color="blue"> <b>Exercise<br></b></font>

<font color="#9900FF"> Sorting Arrays in Descending Order</font>


##### <font color="#006666">Sorting 2D Arrays<br></font>

In [ ]:
# Creating a 2D array
arr_2d = np.array([[9, 1, 2], [6, 4, 5]])

# Sorting along the rows (axis=1)
sorted_rows = np.sort(arr_2d, axis=1)
print("Sorted 2D array along rows:")
print(sorted_rows)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Sorting along the columns (axis=0)
sorted_cols = np.sort(arr_2d, axis=0)
print("Sorted 2D array along columns:")
print(sorted_cols)
# Output:
# [[3 1 2]
#  [6 4 5]]



##### <font color="#006666">Searching Arrays<br></font>

Using where()<br>

----> The <b>where()</b> function returns the indices of elements that meet a specified condition.

In [ ]:
# Creating an array
arr = np.array([10, 15, 20, 25, 30])

# Finding indices of elements greater than 20
indices = np.where(arr > 20)
print("Indices where elements are greater than 20:", indices)
# Output: Indices where elements are greater than 20: (array([3, 4]),)


Using argmax() and argmin()<br>

<b>argmax():</b> Returns the index of the maximum element in the array.<br>

<b>argmin():</b> Returns the index of the minimum element in the array.

In [ ]:
# Using argmax() to find the index of the maximum element
max_index = np.argmax(arr)
print("Index of the maximum element:", max_index)
# Output: Index of the maximum element: 4

# Using argmin() to find the index of the minimum element
min_index = np.argmin(arr)
print("Index of the minimum element:", min_index)
# Output: Index of the minimum element: 0

<font color="blue"> <b>Exercise<br></b></font>

<font color="#9900FF">Finding Maximum Element in an array without using Built-in Functions..?<br>
Finding Minimum Element in an array without using Built-in Functions..?</font>